name: Cypress Tests with Allure and Slack

on:
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Install dependencies
        run: npm install

      - name: 🧪 Run Cypress tests with Allure enabled
        run: |
          npx cypress run --env allure=true
        continue-on-error: true # allow failures to be caught for Slack notification

      - name: 🧾 Generate Allure Report
        run: |
          npx allure generate allure-results --clean -o allure-report || echo "Skipping if no results"

      - name: 📤 Upload Allure Report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: 📣 Send Slack notification
        if: always() # run this step even if previous steps fail
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          STATUS="passed"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="failed"
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \"🔔 *Cypress tests ${STATUS}* on *${{ github.ref_name }}*\n🔗 <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow & Allure Report Artifacts>\"
          }" $SLACK_WEBHOOK_URL

